//
//  MoviesByOccasion.swift
//  Moobee Boyz
//
//  Created by Sean Bamford on 12/17/18.
//  Copyright © 2018 COMP401. All rights reserved.
//

import Foundation

class MoviesByOccasion {
    
    static var Christmas : [String] = [
        "Noelle",
        "Margie Claus",
        "The Nutcracker and the Four Realms",
        "The Grinch",
        "Anna and the Apocalypse",
        "The Star",
        "The Man Who Invented Christmas",
        "Just Getting Started",
        "Daddy's Home 2",
        "A Bad Moms Christmas",
        "Why Him?",
        "Office Christmas Party",
        "Better Watch Out",
        "Bad Santa 2",
        "Almost Christmas",
        "The Night Before",
        "Love the Coopers",
        "Krampus",
        "Carol",
        "All Through the House",
        "A Christmas Horror Story",
        "Saving Christmas",
        "A Merry Friggin' Christmas",
        "The Christmas Candle",
        "The Best Man Holiday",
        "Iron Man 3",
        "Christmas Cruelty!",
        "Black Nativity",
        "Angels Sing",
        "A Madea Christmas",
        "Silent Night",
        "Christmas in Compton",
        "Arthur Christmas",
        "A Very Harold & Kumar 3D Christmas",
        "The Nutcracker in 3D",
        "Rare Exports: A Christmas Tale",
        "Home for Christmas",
        "Everybody's Fine",
        "Nothing like the Holidays",
        "Four Christmases",
        "A Christmas Tale (Un conte de Noël)",
        "What Would Jesus Buy?",
        "This Christmas",
        "Fred Claus",
        "Christmas Cottage",
        "Unaccompanied Minors",
        "The Santa Clause 3: The Escape Clause",
        "The Nativity Story",
        "The Holiday",
        "Deck the Halls",
        "Black Christmas",
        "The Ice Harvest",
        "The Family Stone",
        "Santa's Slay",
        "Kiss Kiss Bang Bang",
        "Just Friends",
        "Joyeux Noël",
        "The Polar Express",
        "Surviving Christmas",
        "Noel",
        "Christmas with the Kranks",
        "Love Actually",
        "Elf",
        "Blizzard",
        "Bad Santa",
        "The Santa Clause 2",
        "Friday After Next",
        "Serendipity",
        "The Family Man",
        "Reindeer Games",
        "Dr. Seuss' How the Grinch Stole Christmas",
        "Go",
        "Eyes Wide Shut",
        "Jack Frost    1998",
        "I'll Be Home for Christmas",
        "The Preacher's Wife",
        "The Long Kiss Goodnight",
        "Jingle All the Way",
        "How the Toys Saved Christmas",
        "While You Were Sleeping",
        "Trapped in Paradise",
        "The Santa Clause",
        "The Ref",
        "Mixed Nuts",
        "Miracle on 34th Street",
        "The Nightmare Before Christmas",
        "Look Who's Talking Now",
        "Home Alone 2: Lost in New York",
        "Batman Returns",
        "The Last Boy Scout",
        "Hook",
        "All I Want for Christmas",
        "Home Alone",
        "Die Hard 2: Die Harder",
        "Prancer",
        "National Lampoon's Christmas Vacation",
        "3615 code Père Noël",
        "Scrooged",
        "Ernest Saves Christmas",
        "Die Hard",
        "The Princess Bride",
        "Silent Night, Deadly Night Part 2",
        "Lethal Weapon",
        "Less Than Zero",
        "The Sure Thing",
        "Santa Claus: The Movie",
        "Rocky IV",
        "One Magic Christmas",
        "Trancers",
        "Silent Night, Deadly Night",
        "Gremlins",
        "Don't Open till Christmas",
        "Trading Places",
        "Merry Christmas, Mr. Lawrence",
        "A Christmas Story",
        "Female Trouble",
        "Black Christmas",
        "The Christmas Kid",
        "Fitzwilly",
        "Pocketful of Miracles",
        "Babes in Toyland",
        "Santa Claus",
        "We're No Angels",
        "The Night of the Hunter",
        "White Christmas",
        "Susan Slept Here",
        "The Holly and the Ivy",
        "The Lemon Drop Kid",
        "Trail of Robin Hood",
        "The Great Rupert",
        "Mr. Soft Touch",
        "Holiday Affair",
        "3 Godfathers",
        "The Bishop's Wife",
        "Miracle on 34th Street",
        "Lady in the Lake",
        "It Happened on Fifth Avenue",
        "Christmas Eve",
        "It's a Wonderful Life",
        "The Bells of St. Mary's",
        "Christmas in Connecticut",
        "The Curse of the Cat People",
        "Meet Me in St. Louis",
        "Christmas Holiday",
        "The Man Who Came to Dinner",
        "Holiday Inn",
        "Meet John Doe",
        "The Shop Around the Corner",
        "The Blue Bird",
        "Remember the Night",
        "Beyond Tomorrow",
        "Bachelor Mother",
        "Love Finds Andy Hardy",
        "Heidi",
        "The Thin Man",
        "Babes in Toyland",
        "A Bill of Divorcement",
        "The Unholy Three",
    ]
    
    static var Halloween : [String] = [
        "Arsenic and Old Lace",
        "Boo! A Madea Halloween",
        "Boo 2! A Madea Halloween",
        "Grumpier Old Men",
        "Carry On Screaming",
        "A Cinderella Story",
        "Hocus Pocus",
        "The Hollywood Knights",
        "Idle Hands",
        "Mean Girls",
        "The Midnight Hour",
        "Once Bitten",
        "Son of the Mask",
        "Spaced Invaders",
        "Stan Helsing",
        "Wasabi Tuna",
        "Scary Movie",
        "Scary Movie 2",
        "Scary Movie 3",
        "Scary Movie 4",
        "Scary Movie 5",
        "31",
        "All Hallows' Eve",
        "All Hallows Eve: October 30th",
        "All Hallows Evil: Lord of the Harvest",
        "Always from Darkness",
        "American Horror House",
        "The Amityville Horror",
        "The Amityville Horror",
        "Babysitter Massacre",
        "Bad Reputation",
        "The Barn",
        "Black Pumpkin",
        "The Blair Witch Project",
        "Bloody Bobby: The Fall Creek Valley Massacre",
        "Boo",
        "Cemetery of Terror (a.k.a. Cementerio del terror)",
        "The Changeling",
        "The Clown Murders",
        "Clownhouse",
        "The Chilling",
        "The Collection",
        "The Collingswood Story",
        "Creepshow",
        "Creepshow 2",
        "Creepy Campfire Stories",
        "Dark Night of the Scarecrow",
        "Dark Walker",
        "Deadly Friend",
        "Demonic Toys",
        "Donnie Darko",
        "The Exorcist",
        "Flatliners",
        "Flesheater",
        "Flick",
        "Ginger Snaps",
        "Ginger Snaps 2: Unleashed",
        "Ginger Snaps Back: The Beginning",
        "Grave Halloween",
        "Gravy",
        "The Guest",
        "Hack O'Lantern (a.k.a. Halloween Night)",
        "Halloween Hell",
        "Halloween Night",
        "Halloweenight",
        "Hellbent",
        "Hell Fest",
        "Hell Fire",
        "Hellions",
        "Holidays",
        "The Hollow",
        "Hollow Gate",
        "House II: The Second Story",
        "House of 1000 Corpses",
        "House of Fears",
        "The House with a Clock in Its Walls",
        "The Houses October Built",
        "The Houses October Built 2",
        "I Was a Teenage Werewolf",
        "In Search of Lovecraft",
        "The Invasion",
        "Jack-O",
        "The Kiss",
        "Lady in White",
        "The Little Girl Who Lives Down the Lane",
        "May",
        "The Midnight Hour",
        "Mischief Night (2013; Travis Baker)",
        "Mischief Night (2013; Richard Schenkman)",
        "Monster Night",
        "Murder Party",
        "Pet Sematary",
        "Pet Sematary Two",
        "Poltergeist",
        "Poltergeist",
        "Poltergeist II: The Other Side",
        "Poltergeist III",
        "The Predator",
        "Primal Rage",
        "The Pumpkin Karver",
        "The Rage: Carrie 2",
        "The Return of Count Yorga",
        "Return of the Living Dead: Rave to the Grave",
        "Satan's Little Helper",
        "The Scarehouse",
        "Scary Movie",
        "Silver Bullet",
        "Sinister",
        "Sleepy Hollow",
        "Slugs",
        "Tales of Halloween",
        "Total Skull Halloween",
        "Trick or Treat",
        "Trick or Treats",
        "Trick 'r Treat",
        "V/H/S (segment 10/31/98)",
        "Volumes of Blood",
        "We Need to Talk About Kevin",
        "Wrong Turn 5: Bloodlines",
        "Halloween (1978)",
        "Halloween II (1981)",
        "Halloween III: Season of the Witch",
        "Halloween 4: The Return of Michael Myers",
        "Halloween 5: The Revenge of Michael Myers",
        "Halloween: The Curse of Michael Myers",
        "Halloween H20: 20 Years Later",
        "Halloween: Resurrection",
        "Halloween (2007)",
        "Halloween II (2009)",
        "Halloween (2018)",
        "Night of the Demons (1988)",
        "Night of the Demons 2",
        "Night of the Demons 3",
        "Night of the Demons (2009)",
        "A-Haunting We Will Go",
        "The Addams Family",
        "Addams Family Values",
        "The Adventures of Ichabod and Mr. Toad",
        "Alpha and Omega: The Legend of the Saw Tooth Cave",
        "Alvin and the Chipmunks Meet Frankenstein",
        "Alvin and the Chipmunks Meet the Wolfman",
        "Batman Unlimited: Monster Mayhem",
        "Bewitched",
        "Boo to You Too! Winnie the Pooh",
        "The Book of Life",
        "Bouncing Babies",
        "The Boy Who Cried Werewolf",
        "Broom-Stick Bunny",
        "Bugs Bunny's Howl-oween Special",
        "Casper",
        "Casper: A Spirited Beginning",
        "Casper Meets Wendy",
        "Casper's Halloween Special",
        "Corn on the Cop",
        "Corpse Bride",
        "Curious George: A Halloween Boo Fest",
        "Dear Dracula",
        "Diary of a Wimpy Kid",
        "Disney Sing Along Songs: Happy Haunting",
        "Disney's Halloween Treat",
        "The Dog Who Saved Halloween",
        "Double, Double, Toil and Trouble",
        "Ernest Scared Stupid",
        "Ella Enchanted",
        "E.T. the Extra-Terrestrial",
        "The Fat Albert Halloween Special",
        "The Flintstones Meet Rockula and Frankenstone",
        "Frankenstein and Me",
        "Frankenweenie",
        "Fright to the Finish",
        "Fun Size",
        "Garfield's Halloween Adventure",
        "Ghost Squad",
        "Girl vs. Monster",
        "Goosebumps 2: Haunted Halloween",
        "Grow Up, Tony Phillips",
        "Halloween",
        "Halloween Is Grinch Night",
        "The Halloween That Almost Wasn't",
        "The Halloween Tree",
        "Halloween with the New Addams Family",
        "Halloweentown",
        "Halloweentown II: Kalabar's Revenge",
        "Halloweentown High",
        "Harry Potter and the Sorcerer's Stone",
        "Hocus Pocus",
        "Hotel Transylvania",
        "Hotel Transylvania 2",
        "I Downloaded a Ghost",
        "It's the Great Pumpkin, Charlie Brown",
        "The Karate Kid",
        "Kenny & Company",
        "The Little Vampire",
        "Matilda",
        "Mickey's House of Villains",
        "Monsters, Inc.",
        "Monster House",
        "Monster Night",
        "The Monster Squad",
        "Monsters vs. Aliens: Mutant Pumpkins from Outer Space",
        "Mostly Ghostly",
        "Mostly Ghostly: Have You Met My Ghoulfriend?",
        "Mostly Ghostly: One Night in Doom House",
        "Mr. Magorium's Wonder Emporium",
        "Night of the Living Carrots",
        "The Nightmare Before Christmas",
        "ParaNorman",
        "Phantom of the Megaplex",
        "Pooh's Heffalump Halloween Movie",
        "Recess: Taking the Fifth Grade",
        "Return to Halloweentown",
        "R.L. Stine's Monsterville: Cabinet of Souls",
        "R.L. Stine's The Haunting Hour: Don't Think About It",
        "Room on the Broom",
        "Something Wicked This Way Comes",
        "Scared Shrekless",
        "The Scream Team",
        "Scooby-Doo",
        "Scooby-Doo and the Goblin King",
        "Scooby-Doo 2: Monsters Unleashed",
        "Scooby-Doo! Spooky Scarecrow",
        "Scruff's Halloween",
        "The Smurfs: The Legend of Smurfy Hollow",
        "Song of the Sea",
        "Spaced Invaders",
        "Spookley the Square Pumpkin",
        "Spooky Buddies",
        "Tom & Jerry Halloween Special",
        "Toy Story of Terror!",
        "Trick or Treat",
        "Twitches",
        "Twitches Too",
        "Under Wraps",
        "When Good Ghouls Go Bad",
        "The Worst Witch",
        "Scooby-Doo and the Witch's Ghost",
        "Affliction",
        "American Splendor",
        "Batman Forever",
        "Big Daddy",
        "Cowboy Bebop: The Movie",
        "The Crow",
        "Cry Wolf",
        "Donnie Darko",
        "Ed Wood",
        "Ironweed",
        "Jack the Bear",
        "Jack Reacher: Never Go Back",
        "Kotch",
        "Kramer vs. Kramer",
        "Liberty Heights",
        "Lost in Translation",
        "Meet Me in St. Louis",
        "Mischief Night",
        "Mysterious Skin",
        "The Night That Panicked America",
        "Nightdreams",
        "Ordinary People",
        "A Perfect World",
        "Practical Magic",
        "The Predator",
        "Showgirls",
        "St. Elmo's Fire",
        "Sweet Hearts Dance",
        "Teenage Mutant Ninja Turtles: Out of the Shadows",
        "To Kill a Mockingbird",
        "Twin Falls Idaho",
    ]
    
    static var WW1_WW2 : [String] = [
        "Bethune: The Making of a Hero",
        "Blood Oath",
        "Dr. Petiot",
        "Europa Europa",
        "Good Evening, Mr. Wallenberg",
        "Hiroshima: Out of the Ashes",
        "Korczak",
        "A Man Called Sarge",
        "Memphis Belle",
        "The Nasty Girl",
        "Spymaker: The Secret Life of Ian Fleming",
        "The Boys from St. Petri",
        "The Child of Man (Son of Man)",
        "December (An Innocent War)",
        "Europa (Zentropa)",
        "For the Boys",
        "Just Beyond That Forest",
        "Mediterraneo",
        "The Naked Trees",
        "The Quarrel",
        "Rhapsody in August",
        "Warsaw - Year 5703",
        "All That Really Matters",
        "A Day in October",
        "A Midnight Clear (Section 44)",
        "Ring with a Crowned Eagle",
        "Shining Through",
        "For the Moment",
        "The Last Lieutenant (The Second Lieutenant)",
        "The Mirror",
        "The Puppetmaster",
        "Schindler's List",
        "Stalag Luft",
        "Stalingrad",
        "Swing Kids",
        "Tear of the Prince of Darkness (Satan's Tear)",
        "The Ascent",
        "A Day Before Dawn",
        "Dear Goddamned Friends",
        "Childhood Enemies",
        "Don't Cry, Nanking (Nanjing 1937)",
        "The Great Commander Georgy Zhukov",
        "Hiroshima",
        "Holy Week",
        "Just a Girl",
        "The Last Bullet",
        "Mission of the Shark: The Saga of the U.S.S. Indianapolis",
        "Red Cherry",
        "Sahara (Desert Storm)",
        "Truman",
        "The Tuskegee Airmen",
        "Underground",
        "The Partisans",
        "The Border",
        "The Brylcreem Boys",
        "The English Patient",
        "Hamsun",
        "Mother Night",
        "The Ogre",
        "On Dangerous Ground",
        "Over Here",
        "The Ring (Danielle Steel's The Ring)",
        "The Seventh Room (The Seventh Chamber)",
        "Sunset at Chaophraya",
        "Bent",
        "The Devil's General",
        "The Island on Bird Street",
        "The Land Girls",
        "Life Is Beautiful",
        "Lucie Aubrac",
        "Paradise Road",
        "Deserter's Gold",
        "Dr. Akagi",
        "Little Teachers",
        "Miracle at Midnight",
        "Pride: The Fateful Moment",
        "Saving Private Ryan",
        "The Thin Red Line",
        "When Trumpets Fade",
        "Aimée & Jaguar",
        "All My Loved Ones",
        "Ambush",
        "Bleiburg",
        "The End of the Affair",
        "Gloomy Sunday",
        "Jakob the Liar",
        "Lover's Grief over the Yellow River (Heart of China)",
        "Moloch",
        "Sunshine",
        "Tea with Mussolini",
        "Bonhoeffer: Agent of Grace",
        "Devils on the Doorstep",
        "Divided We Fall",
        "Johnny the Partisan",
        "Judgement of Franciszek Klos",
        "Lt. Adnan",
        "Malena",
        "Markova: Comfort Gay",
        "Nuremberg",
        "The Sky Is Falling",
        "Spring of Life",
        "U-571",
        "As Far as My Feet Will Carry Me",
        "Band of Brothers",
        "The Bunker (The Bunker: The Evil Is Within)",
        "Captain Corelli's Mandolin",
        "Charlotte Gray",
        "Conspiracy",
        "Dark Blue World",
        "The Days of Rage: Cefalonia",
        "Enemy at the Gates",
        "Enigma",
        "Firefly",
        "The Grey Zone",
        "H Story",
        "In the Bosom of the Enemy",
        "The Ones With White Lips - The Forgotten",
        "Pearl Harbor",
        "Purple Sunset",
        "Taking Sides",
        "To End All Wars",
        "Uprising",
        "Varian's War",
        "The War Bride (Love and War)",
        "Yamashita: The Tiger's Treasure",
        "Below",
        "Black Angel",
        "The Cuckoo",
        "El Alamein: The Line of Fire",
        "The Gathering Storm",
        "The Good War (Texas '46",
        "Hart's War",
        "Monsieur Batignole",
        "Perlasca, The Courage of a Just Man",
        "The Pianist",
        "Safe Conduct",
        "Silent Night",
        "The Star",
        "Twin Sisters",
        "Two Men Went to War",
        "The War Is Over",
        "Windtalkers",
        "Bon Voyage",
        "Entrusted",
        "Paloh",
        "Pornography",
        "Resistance",
        "Rosenstrasse",
        "Saints and Soldiers",
        "Spy Sorge",
        "Strange Gardens",
        "Strayed",
        "Želary",
        "Aishite Imasu 1941: Mahal Kita",
        "The Aryan Couple",
        "Beyond the Front Line",
        "The Cadets",
        "The Call of the River",
        "Downfall",
        "Dunkirk",
        "Edelweiss Pirates",
        "The Face of Jizo",
        "The Fallen (Letters From The Dead)",
        "Freelance Assignment",
        "Head in the Clouds",
        "Our Own",
        "Ike: Countdown to D-Day",
        "Il Duce Canadese",
        "In Enemy Hands (U-Boat)",
        "Island at War",
        "Long Dark Night",
        "Napola: Hitler's Elite (Before the Fall)",
        "The Ninth Day",
        "Operation Valkyrie",
        "Purple Butterfly",
        "Straight Into Darkness",
        "Cephalonia",
        "Everything Is Illuminated",
        "Forest of the Gods",
        "Freelance Assignment 2",
        "The Great Raid",
        "The Heart in the Pit",
        "The Last Days",
        "The Last Drop",
        "Men in White",
        "Moscow Says, Please Note",
        "Mother of Mine",
        "Mussolini's Daughter",
        "Netaji Subhas Chandra Bose: The Forgotten Hero (Bose: The Forgotten Hero)",
        "Only the Brave",
        "On the Mountain of Tai Hang",
        "Promise",
        "Sophie Scholl – The Final Days",
        "Speer and Hitler: The Devil's Architect",
        "The Strait Story",
        "The Sun",
        "Valiant",
        "The White Countess",
        "Yamato",
        "Bastards",
        "Beautiful Dreamer",
        "Black Book",
        "Days of Glory",
        "Dresden",
        "Flags of Our Fathers",
        "Ghetto",
        "The Good Battle - Don Pietro Pappagallo",
        "The Good German",
        "The Haunted Airman",
        "Kokoda",
        "The Last Days",
        "The Last Train",
        "Letters from Iwo Jima",
        "Mafalda of Savoy",
        "Military Intelligence and You!",
        "Remembrance: A Soldier's Story",
        "Transit",
        "The Tokyo Trial",
        "American Pastime",
        "Atonement",
        "The Counterfeiters",
        "Curtin (TV)",
        "For Those We Love",
        "Katyn    Katyń",
        "Lust, Caution",
        "Mein Führer: The Truly Truest Truth About Adolf Hitler (My Führer)",
        "The Poet (Hearts of War)",
        "The Great War",
        "Surviving with Wolves",
        "Tali-Ihantala 1944",
        "Tomorrow We're Going to the Movies",
        "Waiting for Dublin",
        "Australia",
        "Blitzkrieg: Escape from Stalag 69",
        "Blood of the Losers",
        "The Boy in the Striped Pyjamas",
        "The Bridge",
        "Broken Sun",
        "Gruber's Journey",
        "The Children of Huang Shi",
        "Defiance",
        "11th of November",
        "Female Agents",
        "Flame and Citron",
        "Good",
        "Ip Man",
        "Max Manus: Man of War",
        "Miracle at St. Anna",
        "The Reader",
        "Spring 1941",
        "Tobruk",
        "Valkyrie",
        "Watch on the Rhine",
        "The Wedding Song",
        "Wild Blood",
        "Winter in Wartime",
        "A Woman in Berlin (Anonyma: A Woman in Berlin)",
        "The Army of Crime",
        "Attack on Leningrad",
        "City of Life and Death (Nanjing! Nanjing!)",
        "Cow",
        "The Diary of Anne Frank",
        "Everyman's War",
        "Inglourious Basterds",
        "Into the Storm",
        "John Rabe",
        "Last Operations Under the Orion",
        "The Man Who Will Come",
        "The Message",
        "1941",
        "The Priest",
        "Protector",
        "Small Island",
        "Brest Fortress (Fortress of War)",
        "Burnt by the Sun 2",
        "Caterpillar",
        "Death and Glory in Changde",
        "The Debt",
        "East Wind Rain",
        "Habermann",
        "Heaven is on Fire (The Sky is On Fire)",
        "A Jewish Girl in Shanghai",
        "Joanna",
        "The King's Speech",
        "Legend of the Fist: The Return of Chen Zhen",
        "The Edge",
        "The Pacific",
        "The Round Up",
        "Sarah's Key (Her Name was Sarah)",
        "Sisters of War",
        "Spoils of War",
        "Storming Juno",
        "Under the Roman Sky (Pope Pius XII)",
        "Venice",
        "The Way Back",
        "Age of Heroes",
        "Angel of Budapest",
        "Auschwitz",
        "The Consul of Bordeaux",
        "Webseries: Heroes",
        "The Frontier",
        "Gandhi to Hitler (Dear Friend Hitler)",
        "General Della Rovere",
        "In Another Lifetime",
        "In Darkness",
        "Isoroku Yamamoto, the Commander-in-Chief of the Combined Fleet",
        "Ispansi!",
        "Liberation",
        "Lidice",
        "Little Iron Men",
        "The Lost Valentine",
        "My Way",
        "Oba: The Last Samurai (Miracle of the Pacific: The Man Called Fox)",
        "The Sinking of the Laconia",
        "This Life",
        "Three to Dance",
        "Back to 1942",
        "The Flowers of War",
        "Into the White (Comrade)",
        "Lore",
        "Red Tails",
        "Saints and Soldiers: Airborne Creed",
        "The Book Thief",
        "1939 Battle of Westerplatte",
        "Death March",
        "Emperor",
        "The Railway Man",
        "Road 47",
        "Stalingrad",
        "The Wind Rises",
        "Bomb Girls: Facing the Enemy",
        "Diplomacy",
        "Fury",
        "Head High. The Martyrs of Fiesole",
        "The Imitation Game",
        "Italia's Secret",
        "The Monuments Men",
        "Parer's War",
        "Saints and Soldiers: The Void",
        "Suite Française",
        "Unbroken",
        "Walking with the Enemy",
        "Warsaw 44",
        "Dear Elza!",
        "Stones for the Rampart",
        "9. April",
        "1944",
        "Battle for Sevastopol",
        "The Emperor in August",
        "Felix Manalo",
        "The Fence",
        "Hundred Regiments Offensive",
        "Land of Mine",
        "Little Boy",
        "Son of Saul",
        "War Pigs",
        "28 panfilovtsev",
        "Dad's Army",
        "Allied",
        "Anthropoid",
        "Fanny's Journey",
        "Hacksaw Ridge",
        "My Honor Was Loyalty",
        "Railroad Tigers",
        "Their Finest",
        "Tomodachi",
        "USS Indianapolis: Men of Courage",
        "Volhynia",
        "At War, for Love",
        "Rangoon",
        "Darkest Hour",
        "Dunkirk",
        "Raag Desh",
        "The Unknown Soldier",
        "The Man with the Iron Heart",
        "Red Land",
        "Air Strike (Unbreakable Spirit)",
        "The Guernsey Literary and Potato Peel Pie Society",
        "Operation Finale",
    ]
    
    static var Classic : [String] = [
        "Casablanca",
        "The Grapes of Wrath",
        "Black Narcissus",
        "It's a Wonderful Life",
        "Day of Wrath",
        "Bicycle Thieves",
        "Citizen Kane",
        "The Great Dictator",
        "Double Indemnity",
        "The Pride of the Yankees",
        "Le Corbeau",
        "Pinocchio",
        "The Maltese Falcon",
        "White Heat",
        "The Third Man",
        "The Children Are Watching Us",
        "49th Parallel",
        "Bambi",
        "To Have and Have Not",
        "Rebecca",
        "Thieves' Highway",
        "The Treasure of the Sierra Madre",
        "The Big Sleep",
        "For Whom the Bell Tolls",
        "Ossessione",
        "Ivan the Terrible, Part I",
        "Dumbo",
        "Deception",
        "Notorious",
        "The Postman Always Rings Twice",
        "Murder, My Sweet",
        "Beauty and the Beast",
        "The Ox-Bow Incident",
        "Sullivan's Travels",
        "How Green Was My Valley",
        "And Then There Were None",
        "The Uninvited",
        "The Woman in the Window",
        "Green for Danger",
        "A Matter of Life and Death",
        "Great Expectations",
        "Quai des Orfèvres",
        "Journey Into Fear",
        "A Walk in the Sun",
        "Dead of Night",
        "Caesar and Cleopatra",
        "The Quiet Duel",
        "Key Largo",
        "Monsieur Verdoux",
        "The Devil and Daniel Webster",
        "Out of the Past",
        "The Fallen Idol",
        "They Were Expendable",
        "Joan of Arc",
        "Hamlet",
        "Drunken Angel",
        "All the King's Men",
        "The Strange Love of Martha Ivers",
        "The Devil and Miss Jones",
        "The Wolf Man",
        "Macbeth",
        "High Sierra",
        "Odd Man Out",
        "Somewhere in the Night",
        "The Life and Death of Colonel Blimp",
        "The Thief of Bagdad",
        "The Seventh Victim",
        "Stray Dog",
        "Fantasia",
        "His Girl Friday",
        "Our Town",
        "Dr. Jekyll and Mr. Hyde",
        "Adam's Rib",
        "Twelve O'Clock High",
        "National Velvet",
        "Arabian Nights",
        "Sahara",
        "Cat People",
        "The Talk of the Town",
        "Sorry, Wrong Number",
        "Spellbound",
        "Sergeant York",
        "The Letter",
        "Mildred Pierce",
        "Saboteur",
        "The Magnificent Ambersons",
        "The Bank Dick",
        "Pride and Prejudice",
        "Oliver Twist",
        "The Body Snatcher",
        "The Seventh Cross",
        "The Bishop's Wife",
        "Dragonwyck",
        "Dark Passage",
        "Jane Eyre",
        "State of the Union",
        "The Spiral Staircase",
        "The Picture of Dorian Gray",
        "Rope",
        "Miracle on 34th Street",
    ]
    
    static var NewYear : [String] = [
        "Assault on Precinct 13",
        "Comed",
        "Are We There Yet?",
        "Bachelor Mother",
        "Carnival Night",
        "Four Rooms",
        "Get Crazy",
        "Ghostbusters II",
        "The Gold Rush",
        "The Hudsucker Proxy",
        "New Year's Day",
        "Party Party",
        "Radio Days",
        "Trading Places",
        "200 Cigarettes",
        "About a Boy",
        "Bridge and Tunnel",
        "Diner",
        "A Long Way Down",
        "Mermaids",
        "More American Graffiti",
        "New Year's Day",
        "Peter's Friends",
        "Sweet Hearts Dance",
        "Crime/caper/heis",
        "After the Thin Man",
        "Better Luck Tomorrow",
        "Dhoom",
        "Entrapment",
        "The Godfather Part II",
        "Little Caesar",
        "Money Train",
        "Ocean's 11",
        "The Poseidon Adventure",
        "Beyond the Poseidon Adventure",
        "The Poseidon Adventure",
        "Poseidon",
        "Dram",
        "54",
        "Boogie Nights",
        "Cavalcade",
        "The Divorcee",
        "Fruitvale Station",
        "I'll Be Seeing You",
        "Looking for Mr. Goodbar",
        "Middle of the Night",
        "My Reputation",
        "The New Year",
        "New Year's Eve",
        "One Way Passage",
        "The Passionate Friends",
        "Penny Serenade",
        "Pollock",
        "Il Posto",
        "Splendor in the Grass",
        "'Til We Meet Again",
        "Two Lovers",
        "Yanks",
        "Antisocial",
        "The Children",
        "Day Watch",
        "End of Days",
        "Ghostkeeper",
        "Holidays",
        "The Mephisto Waltz",
        "Mystery of the Wax Museum",
        "New Year's Evil",
        "The Phantom Carriage",
        "The Phantom Carriage",
        "Rosemary's Baby",
        "Terror Train",
        "Musica",
        "Bundle of Joy",
        "Carnival Night",
        "Get Crazy",
        "Holiday Inn",
        "New Year Adventures of Masha and Vitya",
        "Rent",
        "An Affair to Remember",
        "The Apartment",
        "Baby Cakes",
        "Bachelor Mother",
        "Bridget Jones's Diary",
        "Come Look at Me",
        "Holiday",
        "In Search of a Midnight Kiss",
        "The Irony of Fate",
        "The Irony of Fate 2",
        "New Year's Eve",
        "Remember the Night",
        "Sex and the City: The Movie",
        "Sleepless in Seattle",
        "Someone Like You",
        "Untamed Heart",
        "When Harry Met Sally",
        "While You Were Sleeping",
        "Yolki",
        "Yolki 2",
        "Yolki 3",
        "Yolki 1914",
        "Yolki 5",
        "Alien Nation: Millennium",
        "Doctor Who",
        "Snowpiercer",
        "Strange Days",
        "The Time Machine",
        "The End of Evangelion",
        "Bitter Moon",
        "Night Train to Paris",
        "Survivor",
        "Taboo",
        "Under Suspicion",
    ]

}
